# Generated by Django 4.0.3 on 2022-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('brand', models.CharField(max_length=80, verbose_name='Marque')),
                ('model', models.CharField(max_length=80, verbose_name='Modèle')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Numéro de série')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
            },
        ),
    ]
